### ISSUE TITLE
Support for rust-analyzer.inlayHints.typeHints and rust-analyzer.inlayHints.parameterHints

### ISSUE THREAD

**Issue by typoon** [fannheyward/coc-rust-analyzer#394]
Hello,

With the [added support for decorators](https://github.com/neovim/neovim/pull/12816) on NeoVim is it possible to add support for inlay typeHints? Like the screenshot below, where we have chainingHints (already implemented) and then in the last line we have the typeHints (for vars `a` and `b`)

![type hint](https://aws1.discourse-cdn.com/business5/uploads/rust_lang/original/2X/8/86fb34f56c32de8419b547b5172bf222e44ac246.png)

Thanks!

**Comment by steelx** [comment]
even a variable type hint would be super helpful :)

**Comment by weirongxu** [comment]
> Extend nvim_buf_set_extmark to also set decorations. Decorations are visual properties added upon an extmark. Currently the supported decorations are:
> 
> 	virtual text added at the EOL of the extmark.
> 	highlight the byte extent of the extmark.

https://github.com/neovim/neovim/pull/11745#issue-365342339

As **bfredl** said, the current `nvim_buf_set_extmark` API only supports virtual text and highlight, maybe nvim is currently focusing on related features of treesitter

**Comment by al-jshen** [comment]
![2020-10-18 00-56-19](https://user-images.githubusercontent.com/22137276/96359108-cd691e80-10dc-11eb-8c1a-30ccc0e4093a.png)

Type hints in the middle of the line might be a little confusing (what did you type, what is a type hint) or distracting depending on your color scheme. I don't know if the hints would be treated as normal text (how would that work?) but if not, then there might also be unexpected behaviour when you try to move around. I think what is shown in this picture here might be more useful. The type hints just look like regular chaining hints, and appear at the end of the line. This is https://github.com/nvim-lua/lsp_extensions.nvim with nvim-lsp on neovim 0.5.

**Comment by fannheyward** [comment]
@al-jshen ChainingHint is already supported.

**Comment by typoon** [comment]
@al-jshen Type hints at the end of the line do not seem like a good idea. In the example you gave, there are two variables and a single type hint. The vars could have different types in certain situations, then having to look at the vars and at the end of the line to do the matching makes it harder. Also, if the line is closer to 80 chars (or 99 in rust's case) you have to deal with li e breaks and thing may get messy. Having a color for the type hints that is different from the color of types should be enough. Many editors do it like that and nobody gets confused.

**Comment by al-jshen** [comment]
Chaining hints are only supported for the middle of the chains though, not on the last line with the `;`. There are also no hints for assignments like `let x = 5;`
![2020-10-19 00-02-21](https://user-images.githubusercontent.com/22137276/96400353-7af03680-119e-11eb-8f73-adb8654ce775.png)

Yes, I suppose that separate type hints might be useful. I haven't used any other editors so I don't know what it's like. I guess I'll just have to see when (if?) this is eventually implemented. :)

**Comment by oblitum** [comment]
This decoration API doesn't seem to bring anything new in the sense of https://github.com/neovim/neovim/pull/9496.

**Comment by fannheyward** [comment]
`rust-analyzer.inlayHints.typeHints` is supported in v0.18.0.

**Comment by the10thWiz** [comment]
I would like to see future support for this feature to allow multiple type hints per line. I'm willing to build this myself, but I'm interested to hear some other opinions on the actual implementation.

A simple situation where the current implementation fails: `let (a, b) = (0, "");` This shows `&str`, since rust-analyser reports hints for both, and each one added overwrites previous hints.

A simple solution might be to create an expanding hint, so `let (a, b) = (o, "");` would show `i32 &str` (with appropriate seperators). Another future improvement might be a CocCommand to retrieve them for use in other situations.

**Comment by oblitum** [comment]
@the10thWiz a proper implementation would need https://github.com/neovim/neovim/pull/9496#issuecomment-621591637, but as there's no such thing yet, a current possible implementation could involve usage of conceal, as it's often employed in [LaTeX](https://github.com/KeitaNakamura/tex-conceal.vim), or [Haskell](https://github.com/Twinside/vim-haskellConceal).

**Comment by the10thWiz** [comment]
My suggested (temporary) implementation is to simply add more virtual text to the end of the line. This would likely be assisted by adding multiple separators, one for each type of hint. This would hopefully make it easier to tell what each hint is for.

I have actually already implemented my temporary solution, which looks something like this: `let (a, b) = ("", 0); ‣&str ‣i32` (I'm not really able to take screenshots right now). Basically, there is some extra code that first checks if there's already another hint on the line, and adds it rather than clobbering it.

When/if anti-conceal does stabilize, it would be nice to take advantage of, but until then, we can do reasonably well without. It would be nice to take advantage of param name hints at some point.

**Comment by fannheyward** [comment]
<img width="377" alt="截屏2020-12-10 14 29 40" src="https://user-images.githubusercontent.com/345274/101729980-2610d280-3af4-11eb-8385-770d04506c18.png">

@the10thWiz thanks for your PR.

**Comment by typoon** [comment]
So, I have added a little logic to @the10thWiz change just to show the name of the symbol together with its type so it is easier to see and make sense of it. 

<img width="679" alt="Screen Shot 2020-12-11 at 12 48 18 PM" src="https://user-images.githubusercontent.com/775171/101962336-e7edde80-3bd9-11eb-931f-5e39f68f495e.png">

With this, it gets it pretty close to the ideal solution.

**Comment by the10thWiz** [comment]
An ideal implementation would look something like `‣(&str, i32, f64)`, but this would require some serious work. A much easier improvement would be to add a separate seperator symbol for chaining hints, since they are a return type, not a variable type. The default could be `->`, although there is probably a better UTF-8 character.

If we do want to use `->` for chaining hints, it might be a good idea to set the default type hint separator to `:`, to match rust. However, this might be somewhat confusing and needs some testing.

**Comment by xltan** [comment]
> So, I have added a little logic to @the10thWiz change just to show the name of the symbol together with its type so it is easier to see and make sense of it.
> 
> <img alt="Screen Shot 2020-12-11 at 12 48 18 PM" width="679" src="https://user-images.githubusercontent.com/775171/101962336-e7edde80-3bd9-11eb-931f-5e39f68f495e.png">
> 
> With this, it gets it pretty close to the ideal solution.

I think this is too verbose, can we have an option to get rid of the variable name?

**Comment by xltan** [comment]
Most case, we will only have one variable, which will give you something like this.
```rust
struct SomeStruct;
let some_var = SomeStruct;  ‣some_var: SomeStruct
```

**Comment by fannheyward** [comment]
@xltan `rust-analyzer.inlayHints.typeHintsWithVariable` is added, default `true`, please give it a test.

**Comment by xltan** [comment]
cool, works as expected, thanks👍

**Comment by svenstaro** [comment]
I think this should be reopened as `parameterHints` doesn't seem to be supported yet.

**Comment by fannheyward** [comment]
@svenstaro we can't add parameterHints by now because we can't set text/virtual text _inline_. This needs vim/nvim to add this support.

**Comment by svenstaro** [comment]
Ah, is there some kind of upstream ticket tracking this feature in vim/nvim?

**Comment by fannheyward** [comment]
I don't know.

**Comment by oblitum** [comment]
@svenstaro https://github.com/neovim/neovim/pull/9496#issuecomment-621591637

**Comment by svenstaro** [comment]
Welp, that doesn't look like it's going anywhere soon. Thanks for the reference, though.
