### ISSUE TITLE
TypeError: Cannot read property 'stop' of undefined

### ISSUE THREAD

**Issue by GopherJ** [fannheyward/coc-rust-analyzer#556]
I've had this issue while running `rust-analyzer.upgrade`

it happens on `ctx.checkUpdate()`

**Comment by GopherJ** [comment]
https://github.com/fannheyward/coc-rust-analyzer/blob/31c9f373e33ba6b73eab4b8e2c144ab9d10bb777/src/ctx.ts#L140

**Comment by GopherJ** [comment]
I think this happens if:

1. RA crashed 3 times etc, client is not properly created and connected to RA
2. in this case, if we run `rust-analyzer.upgrade` then it happens

**Comment by Some-Dood** [comment]
I can confirm that this happens to me as well. `coc-rust-analyzer` has been quite unstable for a few weeks now. For reasons I am still trying to figure out, the language server fails to initialize on startup. I keep receiving the notification that "`coc-rust-analyzer` has crashed 5 times... it will not be restarted again".

Since I have the current version of Node installed, I aimed my initial suspicion towards v15's [breaking change where unhandled promise rejections now cause the entire Node process to crash](https://nodejs.medium.com/node-js-v15-0-0-is-here-deb00750f278). I figured that perhaps some unhandled error was quite literally preventing the language server from starting, hence the error message "`coc-rust-analyzer` has crashed 5 times".

However, I must note that `coc-rust-analyzer` still worked perfectly fine when I used it around November (a month after the release of v15). In fact, the last time I was able to successfully initialize and upgrade the language server was back in the `2020-11-30` version. Perhaps we should bisect from here? After that point, the server always fails to initialize, and thus I have not been able to upgrade because of the issue raised by @GopherJ.

Now, I don't think this is strictly an upstream issue because other CoC extensions work perfectly fine for me. I have tried running `:CocUpdate`, yet this initialization issue still persists. Is there any way to look into the logs so that we may have better context on what's causing this issue?

**Comment by fannheyward** [comment]
> the last time I was able to successfully initialize and upgrade the language server was back in the 2020-11-30 version

This is rust-analyzer's release, not coc-rust-analyzer.

**Comment by fannheyward** [comment]
> Cannot read property 'stop' of undefined

coc-rust-analyzer will check and download the latest RA release, then stop and start the server. The error is because the server is not running when do `stop`.

**Comment by Some-Dood** [comment]
Aha! I think I have solved the issue! It turns out that this is all related to #532. Upstream breaking changes from the `rust-analyzer` executable ultimately "deadlocked" the extension from automatically upgrading. This is because `coc-rust-analyzer` needs to be initialized before it can check for new releases. But how would this be possible if `coc-rust-analyzer` cannot start up in the first place? This is where the issue is rooted.

The solution, then, is to manually upgrade the `rust-analyzer` executable. On my Windows machine, `coc-rust-analyzer` downloads the binaries to `%LOCALAPPDATA%\coc\extensions\coc-rust-analyzer-data`. Then, I simply overwrote the `rust-analyzer.exe` with the [latest stable release](https://github.com/rust-analyzer/rust-analyzer/releases/) of `rust-analyzer`. Everything should be smooth sailing from there.

**Comment by GopherJ** [comment]
@Some-Dood Hi, I think `coc-rust-analyzer` is pretty stable on the common functionalities, I didn't have problems while using it. This issue just happen in small cases like:

1. you can a pretty old version of coc-rust-analyzer and rust-analyzer
2. you try to upgrade while language client isn't created due to RA's upgrade for LSP3.16

**Comment by Some-Dood** [comment]
Don't worry! I've sorted things out with my setup. Thanks for the suggestions. I suppose the issue you raised is just an inherent limitation of CoC extensions. It's like a chicken-and-egg problem: how can the extension patch the `rust-analyzer` executable if the extension cannot be initialized to begin with?

With that said, perhaps a good step forward is to give the user the option to check for `rust-analyzer` updates first before attempting to initialize the server. That way, the extension could successfully start up without being hindered by a broken language server executable.

At the moment, it is the other way around, hence the chicken-and-egg problem. As soon as upstream issues occur, the `coc-rust-analyzer` extension simply cannot start up, thereby "deadlocking" the extension at a broken state.
