### ISSUE TITLE
[feature request]: Support rust-analyzer.highlightingOn config

### ISSUE THREAD

**Issue by cossonleo** [fannheyward/coc-rust-analyzer#8]
To enable highlight rust code

**Comment by fannheyward** [comment]
Yes, rust-analyzer.highlighting is not implemented, because RA use [VSCode Decorations](https://vscode.rocks/decorations/) to make additional highlight, but in vim/nvim, is not support yet.

Neovim has virtual text, which is similar to decorations, but you can't put it inside _real_ text. I'll keep this issue open and stay tuned.

**Comment by oblitum** [comment]
There's on going work on tree-sitter integration in NeoVim, maybe that can help for this.

**Comment by fannheyward** [comment]
Neovim will add decorations API! https://github.com/neovim/neovim/pull/11745

**Comment by oblitum** [comment]
@fannheyward nice! Would support for highlight involve changes do coc extensions alone would coc.nvim have to get improved for it?

**Comment by tdejager** [comment]
@fannheyward Why does the semantic highlighting for cxx using clangd, another of your great projects ;), not require the mentioned neovim feature?

**Comment by fannheyward** [comment]
@tdejager semantic highlighting and inlay hints are different things. We can add semanticTokens when LSP 3.16 released.

**Comment by mlvzk** [comment]
> Neovim will add decorations API! [neovim/neovim#11745](https://github.com/neovim/neovim/pull/11745)

seems like it got replaced by this PR https://github.com/neovim/neovim/pull/12816 and got merged. Any plans to add this feature?

**Comment by fannheyward** [comment]
#394
