### ISSUE TITLE
didn't kill rust-analyzer after :q

### ISSUE THREAD

**Issue by GopherJ** [fannheyward/coc-rust-analyzer#838]
recently I noticed that I have many rust-analyzer instances running and if I kill the terminal window, it keeps running behind, sometimes even if I quit vim, it's still there

**Comment by GopherJ** [comment]
watchman is also there:)

**Comment by fannheyward** [comment]
> rust-analyzer instances running and if I kill the terminal window

coc can't shutdown LS in this case.

> even if I quit vim, it's still there

Can't reproduce in my tests.

> watchman is also there even after quiting vim:)

It's expected because watchman will run client-server mode, after you quit vim, watchman server will not be shutdown. https://facebook.github.io/watchman/docs/cli-options.html. You can shutdown the server by `watchman shutdown-server` if you like.

**Comment by GopherJ** [comment]
@fannheyward emm ideed I have something strange, I cannot kill rust-analyzer now, there is always something which restarts it automatically and rust-analyzer has taken up all my cpu.

https://user-images.githubusercontent.com/33961674/129011757-e16f7665-cac5-4010-95fd-8c3f38e8b084.png

**Comment by fannheyward** [comment]
1. `ps` to make sure there is no nvim/coc node/rust-analzyer running
2. open your rust project in nvim
3. after rust-analyzer loading and some edits, quit nvim
4. are there still coc node process and rust-analyzer process?
