### ISSUE TITLE
Color of errors in vim

### ISSUE THREAD

**Issue by OfekShochat** [fannheyward/coc-rust-analyzer#941]
Im using rust-analyzer in vim, and really after some time the color of the errors just irritates me. its bright pink/purple, is there a way to change that?
thanks aot

version: rust-analyzer fd3942eb6 2022-01-31 stable

**Comment by Masterhigure** [comment]
If you are using the CoC rust analyzer, then this is easily fixed by setting `highlight CocErrorSign` to something pleasing. The default is, unless I'm mistaken, `ctermfg=9`. This is red, and it comes from CoC, not from coc-rust-analyzer. If you want them to change their defaults, then this issue belongs there. If you just want to change the colors for you, then your `.vimrc` or wherever you keep your settings is the place to change it.

If the issue is how the red text looks against the background, then that background is taken from `highlight Pmenu`, which has a default that presumably comes from whatever colorscheme you're using.

**Comment by OfekShochat** [comment]
Thanks for the response! Though I forgot I opened the issue and solved it already...
